### ISSUE TITLE
Site unresponsive

### ISSUE THREAD

**Issue by kwickramasekara** [sergio-fry/youtube-fetcher#130] opened 2019-07-29 16:51 UTC
This may not be code related but [https://yt.mazavr.com/](https://yt.mazavr.com/) is showing errors:
![error](https://i.imgur.com/4Hl3HAU.png)

**Comment by sergio-fry** [comment] 2019-08-27 16:45
I have some issues with vps. I have no resources enough to host this site right now. It is not a bug of the software, but infrastructure issue. 

I am closing this

**Closed by sergio-fry** 2019-08-27 16:45 UTC
